### ISSUE TITLE
Creating a website

### ISSUE THREAD

**Issue by ojasvagr123** [murtaza-sadri-19/Breast_Cancer_Prediction#1]
Hi @murtaza-sadri-19!
I can create a website for your Tumor Classification System,
and extend its functionality with enhanced user interface features.

**Comment by murtaza-sadri-19** [comment]
How much time would you need for completion ?

**Comment by ojasvagr123** [comment]
45 days!

**Comment by murtaza-sadri-19** [comment]
Ok go ahead

**Comment by ojasvagr123** [comment]
okay! Thank you !
